pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 1000 || exit 0
      - /usr/bin/setdb provision.restjavad.extramb 1384 || /usr/bin/setdb restjavad.useextramb true || exit 0
runtime_parameters:
  - name: HOST_NAME
    type: metadata
    metadataProvider:
      type: compute
      environment: azure
      field: name
  - name: BIGIP_PASSWORD
    type: static
    value: 'sports-lionize-DOCTRINE1'
  - name: SELF_IP_EXTERNAL
    type: metadata
    metadataProvider:
      type: network
      environment: azure
      field: ipv4
      index: 1
  - name: SELF_IP_INTERNAL
    type: metadata
    metadataProvider:
      type: network
      environment: azure
      field: ipv4
      index: 2
bigip_ready_enabled: []
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.41.0
      extensionHash: 3044e7ea1c8d7e10f51ec14a895374a956b3cbe3251dd6916f4f97da65d0a8e6
    - extensionType: as3
      extensionVersion: 3.48.0
      extensionHash: d732b0e5e462bd5a7b253022ed13dd72afcc30696f0606f4acef47ec02dc31bb
    - extensionType: ts
      extensionVersion: 1.33.0
      extensionHash: 573d8cf589d545b272250ea19c9c124cf8ad5bcdd169dbe2139e82ce4d51a449
    - extensionType: fast
      extensionVersion: 1.25.0
      extensionHash: 434309179af405e6b663e255d4d3c0a1fd45cac9b561370e350bb8dd8b39761f
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Device
        async: true
        label: >-
          Quickstart 3NIC BIG-IP declaration for Declarative Onboarding with PAYG
          license
        Common:
          class: Tenant
          My_DbVariables:
            class: DbVariables
            provision.extramb: 1000
            restjavad.useextramb: true
            ui.advisory.enabled: true
            ui.advisory.color: blue
            ui.advisory.text: BIG-IP LAB
            config.allow.rfc3927: enable
            dhclient.mgmt: disable
          My_Dns:
            class: DNS
            nameServers:
              - 168.63.129.16
          My_Ntp:
            class: NTP
            servers:
              - 0.pool.ntp.org
            timezone: UTC
          My_Provisioning:
            class: Provision
            ltm: nominal
            asm: nominal
          My_System:
            class: System
            autoPhonehome: false
            hostname: '{{{HOST_NAME}}}.local'
          azureuser123:
            class: User
            userType: regular
            partitionAccess:
              all-partitions:
                role: admin
            password: '{{{BIGIP_PASSWORD}}}'
            shell: bash
          default:
            class: ManagementRoute
            gw: 10.0.0.1
            network: default
          dhclient_route1:
            class: ManagementRoute
            gw: 10.0.0.1
            network: 168.63.129.16/32
          azureMetadata:
            class: ManagementRoute
            gw: 10.0.0.1
            network: 169.254.169.254/32
          defaultRoute:
            class: Route
            gw: 10.0.1.1
            network: default
          external:
            class: VLAN
            tag: 4094
            mtu: 1500
            interfaces:
              - name: '1.1'
                tagged: false
          external-self:
            class: SelfIp
            address: '{{{SELF_IP_EXTERNAL}}}'
            vlan: external
            allowService: none
            trafficGroup: traffic-group-local-only
          internal:
            class: VLAN
            tag: 4093
            mtu: 1500
            interfaces:
              - name: '1.2'
                tagged: false
          internal-self:
            class: SelfIp
            address: '{{{SELF_IP_INTERNAL}}}'
            vlan: internal
            allowService: default
            trafficGroup: traffic-group-local-only
    - extensionType: as3
      type: inline
      value:
        class: ADC
        schemaVersion: 3.0.0
        label: Gruyere
        remark: Gruyere
        Tenant_1:
          class: Tenant
          Shared:
            class: Application
            template: shared
            shared_pool:
              class: Pool
              remark: Gruyere pool
              members:
                - serverAddresses:
                    - 10.0.3.4
                  servicePort: 80
              monitors:
                - tcp
          HTTP_Service:
            class: Application
            template: http
            serviceMain:
              class: Service_HTTP
              virtualAddresses:
                - 10.0.1.102
              snat: auto
              policyWAF:
                use: WAFPolicy
              pool: /Tenant_1/Shared/shared_pool
            WAFPolicy:
              class: WAF_Policy
              url: >-
                https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates-v2/v1.4.0.0/examples/quickstart/bigip-configurations/Rapid_Deployment_Policy_13_1.xml
              enforcementMode: blocking
              ignoreChanges: false
          HTTPS_Service:
            class: Application
            template: https
            serviceMain:
              class: Service_HTTPS
              virtualAddresses:
                - 10.0.1.102
              snat: auto
              policyWAF:
                use: WAFPolicy
              pool: /Tenant_1/Shared/shared_pool
              serverTLS:
                bigip: /Common/clientssl
              redirect80: false
            WAFPolicy:
              class: WAF_Policy
              url: >-
                https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates-v2/v1.4.0.0/examples/quickstart/bigip-configurations/Rapid_Deployment_Policy_13_1.xml
              enforcementMode: transparent
              ignoreChanges: false
post_onboard_enabled: []
